### ISSUE TITLE
bundle exec fastlane test doesn't run

### ISSUE THREAD

**Issue by craigedmunds** [trifork/fastlane-plugin-static_assets#1]
Hi, I'm unable to run bundle exec fastlane test in this repo. Any ideas? I followed the instructions in https://github.com/fastlane/fastlane/blob/master/fastlane/docs/PluginsTroubleshooting.md but nothing helped there.

ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
fastlane 2.23.0

Output:

DEBUG [2017-03-28 14:14:30.42]: Checking if there are any plugins that should be loaded...
DEBUG [2017-03-28 14:14:30.42]: Loading 'fastlane-plugin-static_assets' plugin
INFO [2017-03-28 14:14:30.49]: gem 'fastlane-plugin-static_assets' is already installed
+-------------------------------+---------+---------------+
|                      Used plugins                       |
+-------------------------------+---------+---------------+
| Plugin                        | Version | Action        |
+-------------------------------+---------+---------------+
| fastlane-plugin-static_assets | 1.1.0   | static_images |
|                               |         | unused_images |
+-------------------------------+---------+---------------+

INFO [2017-03-28 14:14:30.53]: Driving the lane 'test' 🚀
WARN [2017-03-28 14:14:30.54]: Lane Context:
INFO [2017-03-28 14:14:30.54]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"test"}
ERROR [2017-03-28 14:14:30.54]: Plugin 'static_assets' was not properly loaded, make sure to follow the plugin docs for troubleshooting: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/PluginsTroubleshooting.md
INFO [2017-03-28 14:14:30.54]: Successfully generated documentation at path '/Users/craig/src/react/fastlane-plugin-static_assets/fastlane/README.md'
ERROR [2017-03-28 14:14:30.56]: fastlane finished with errors
/Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane_core/lib/fastlane_core/ui/interface.rb:146:in `user_error!': [!] Plugin 'static_assets' was not properly loaded, make sure to follow the plugin docs for troubleshooting: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/PluginsTroubleshooting.md (FastlaneCore::Interface::FastlaneError)
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:161:in `rescue in trigger_action_by_name'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:155:in `trigger_action_by_name'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:2:in `block in parsing_binding'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /Users/craig/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.23.0/bin/fastlane:20:in `<top (required)>'
	from /Users/craig/.rvm/rubies/ruby-2.3.3/bin/fastlane:22:in `load'
	from /Users/craig/.rvm/rubies/ruby-2.3.3/bin/fastlane:22:in `<main>'
	from /Users/craig/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/craig/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by ghost** [comment]
As far as I know the test action in fastlane plugin is not meant to be runnable. I believe the way to test out a plugin is to try it out kind of like the following:

```
cd my-project-using-fastlane
fastlane add_plugin translation
fastlane install_plugins
# "add the test action to my own Fastfile"
fastlane test
```

**Comment by ghost** [comment]
@craigedmunds - No, I am sorry you are supposed to be able to run the test action. It had the original name of the plugin in there. It is fixed now.
